Camera.name: "theta"
Camera.setup: "monocular"
Camera.model: "fisheye"

Camera.fx: 184
Camera.fy: 182
Camera.cx: 319
Camera.cy: 304

Camera.k1: -0.04158
Camera.k2: 0.046006
Camera.k3: 0.018993
Camera.k4: -0.000383

Camera.fps: 30.0
Camera.cols: 640
Camera.rows: 720

Camera.color_order: "Gray"
